### ISSUE TITLE
Support for https in reverse proxy

### ISSUE THREAD

**Issue by konnik** [lehins/wai-middleware-auth#29]
Is it possible to add support for proxying a website served with https?  Maybe with a new configuration option `protocol: https`? 

```
reverse_proxy:
   host: example.com
   port: 443
   protocol: https
```
